name: cloud_mining
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.1
  bcrypt: ^1.1.3
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.14.0
  dotenv: ^4.2.0
  json_annotation: ^4.9.0
  mailer: ^6.1.2
  mime: ^1.0.5
  mongo_dart: ^0.10.3
  uuid: ^4.4.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
